apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-autenticacao
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-autenticacao
  template:
    metadata:
      labels:
        app: api-autenticacao
    spec:
      containers:
      - name: api-autenticacao-container
        image: lgv1505/fiapautenticacaowebapi:latest
        ports:
        - containerPort: 80

---


apiVersion: v1
kind: Service
metadata:
  name: api-autenticacao-service
  namespace: backend
spec:
  selector:
    app: api-autenticacao
  ports:
    - protocol: TCP
      port: 80 # Altere para a porta desejada
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-autenticacao-ingress
  namespace: backend
spec:
  rules:
  - host: api-autenticacao-kubernets.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-autenticacao-service
            port:
              number: 80